version: "3"
services:
  nginx:
    image: nginx:1.15.7-alpine
    container_name: nginx1.15
    ports:
      - "5000:80"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    networks:
      - default

  php:
    build: .
    container_name: php7.2
    volumes:
      - ./www/:/var/www/html/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:5.7
    container_name: mysql57
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "2240881"
      TZ: "Asia/Shanghai"

  redis:
    image: redis:5.0.3
    container_name: redis5.0
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - default

networks:
  default:
